services:
  - type: web
    plan: free
    name: Ultroid
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 -m pyUltroid & bash startup
    repo: https://github.com/aloramiaa/Ultroid
    branch: master
    envVars:
      - key: SESSION
        sync: false
      - key: REDIS_URI
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: false
